/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const WelcomeLazyImport = createFileRoute("/welcome")();
const HomeLazyImport = createFileRoute("/home")();
const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const WelcomeLazyRoute = WelcomeLazyImport.update({
  path: "/welcome",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/welcome.lazy").then((d) => d.Route));

const HomeLazyRoute = HomeLazyImport.update({
  path: "/home",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/home.lazy").then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/home": {
      preLoaderRoute: typeof HomeLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/welcome": {
      preLoaderRoute: typeof WelcomeLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  HomeLazyRoute,
  WelcomeLazyRoute,
]);

/* prettier-ignore-end */
